<?php if ($this->detiles->iCourseId): ?>
	<script type="text/javascript">
		_gaq_main.push(['_trackEvent', '<?=$this->identity->vUsername?>', 'Course', '<?=$this->detiles->vCoursename ?>']);
		_gaq_custom.push(['_trackEvent', '<?=$this->identity->vUsername?>', 'Course', '<?=$this->detiles->vCoursename ?>']);
	</script>
<h2 class="topbump1">Course : <?=$this->detiles->vCoursename ?></h2>
<p class="topbump"><?php if ($this->detiles->dCourseDateTime > 0) {
	echo $this->detiles->dCourseDateTime;
} ?></p>
<h3 class="topbump">Description :</h3>
<p class="topbump">
	<?= $this->detiles->vDescription?>
</p>
<?php if (count($this->list) > 0) : ?>
	<h3 class="topbump">Classes :</h3>
	<table>
		<tr>
			<th>Sno</th>
			<th>Class</th>
			<th>Time</th>
			<th>Duration</th>
		</tr>
		<?php $rn = 1; foreach ($this->list as $row) : ?>
		<tr>
			<td><?= $rn ?></td>
			<td><?= $row['vClassname'] ?></td>
			<td><?= $row['dClassDateTime'] ?></td>
			<td><?= $row['iDuration'] ?></td>

		</tr>
		<?php

		$rn++;
	endforeach;
		?>
	</table>
	<?php endif; ?>




<?php
endif;